# Generated by Django 2.2.7 on 2019-11-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(default='mdylll@mail.ru', max_length=50, primary_key=True, serialize=False)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('answer', models.CharField(default=None, max_length=30)),
                ('recruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Recruit')),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='sith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sith'),
        ),
    ]
